### ISSUE TITLE
instructions for distributed ROS to README

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_demos#2]
@Veix123 kirjutab juhised, kuidas hostname'iga teha
@mmaao kirjutab juhised, kuidas IP-aadressiga teha

**Comment by Veix123** [comment]
@mmaao @kruusamae, esimene mustand sai siia: 86ef69f919dbf1378700192cd498d7f07f2f25a5

**Comment by kruusamae** [comment]
väga asjalik juhend. nüüd oleks tarvis vaid testida. @mmaao @sandra-schumann võiks äkki mõlemad moodused korra läbi testida.
