### ISSUE TITLE
Add speed control option to joystick

### ISSUE THREAD

**Issue by evamotsh** [robotont/robotont_demos#22]
Currently the joystick has no option to change robot speed. Would be useful to have this feature similarly to how we can change speed in keyboard_teleop.

**Comment by Veix123** [comment]
Partly solved in solved in https://github.com/robotont-demos/demo_teleop via normal and turbo mode. In case more resolution or control over the max velocities is required, lets reopen this ticket in the [demo_teleop](https://github.com/robotont-demos/demo_teleop) repository.
