### ISSUE TITLE
launch-failide nimed ühtlaseks

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_demos#4]
**2d_slam.launch** <- 2d_nav_carto.launch
**2d_slam_display.launch** <- display_2d_mapping.launch
**3d_mapping.launch**
**3d_mapping_display.launch**
**ar_marker_display.launch** <- display_ar_marker.launch

**Comment by kruusamae** [comment]
sellega kaasnevad ka muudatused REAMDE failis

**Comment by mmaao** [comment]
Done, tegin pull requesti ka

**Comment by Veix123** [comment]
Fixed with #5, closing...
